jobs:
  run_tests:
    steps:
      - rn/yarn_install
      - run:
          command: yarn jest
          name: Jest

workflows:
  version: 2
  test-and-deploy:
    jobs:
      — run_tests
      — deploy_android:
        requires:
          — run_tests
          filters:
            branches:
              only:
                — production
                — staging
       — deploy_ios:
        requires:
          — run_tests
          — deploy_android
          filters:
            branches:
              only:
                — production
                — staging
