jobs:
  build:
    macos:
      xcode: "9.0"
  run_tests:
    steps:
      - run:
          command: yarn
          name: Install Packages
      - run:
          command: yarn jest
          name: Jest

workflows:
  version: 2
  test:
    jobs:
      - run_tests
